---
- name: Here we go...
  hosts: homelab

  vars:
    ansible_user: "{{ lookup('env', 'USERNAME') }}"

  roles:
    - services/portainer
    - services/cockpit
    - services/homepage

    #Media
    - services/qbittorrent
    - services/radarr
    - services/sonarr
    - services/prowlarr
    - services/bazarr
    - services/jellyfin
    - services/jellyseerr
