---
- name: Here we go...
  hosts: homelab

  vars:
    ansible_user: "{{ lookup('env', 'USERNAME') }}"

  roles:
    - system/packages
    - role: geerlingguy.docker
      become: true


    - system/user
    - system/machine
    # - geerlingguy.security
