---
- name: Here we go...
  hosts: homelab

  roles:
    - services/portainer
    - services/cockpit
    - services/homepage

    #Media
    - services/qbittorrent
    - services/radarr
    - services/prowlarr
    - services/jellyfin
