---
- name: Here we go...
  hosts: homelab

  roles:
    - system/packages
    - role: geerlingguy.docker
      become: true


    - system/user
    - system/machine


    - services/setup
    - services/portainer
    - services/cockpit
    - services/homepage


    # - geerlingguy.security
