---
- name: Install Python and python3-pip
  become: true
  package:
    name:
      - python3
      - python3-pip
    state: present

- name: Install docker module for Python
  become: true
  pip:
    name:
      - docker
      - docker-compose

- name: Make sure that the docker folders exists
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
  loop:
    - "{{ docker_dir }}"
    - "{{ docker_data_dir }}"
    - "{{ docker_compose_dir }}"

- name: Make sure that the services - compose folders exists
  ansible.builtin.file:
    path: "{{ docker_compose_dir }}/{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
  loop: "{{ services }}"

- name: Make sure that the services - data service folders exists
  ansible.builtin.file:
    path: "{{ docker_data_dir }}/{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
  loop: "{{ services }}"
