#
# Misc
#
username: "orangepi"
shell: /usr/bin/fish
timezone: America/Recife

home_dir: "/home/{{ username }}"

#
# Docker apps
#
docker_dir:         "{{ home_dir }}/docker"
docker_compose_dir: "{{ home_dir }}/docker/composes"
docker_services_dir:    "{{ home_dir }}/docker/services"

# Composes files
containers_config_dir: "{{ playbook_dir }}/containers"

#
# Packages
#
essential_packages:
  - fish
  - git
  - vim
  - htop
  - tmux
  - speedtest-cli
  - stow
  - exa
  - bat
  - lm-sensors
  - tree
  - wget
  - curl
  - traceroute
  - apparmor # Needed by docker in Debian

extra_packages:
  - neofetch
  - neovim
  - ranger

#
# Services
#
services:
  - portainer
  - heimdall
  - homepage
  - qbittorrent
  - radarr
  - sonarr
  - jellyfin
  - prowlarr
  - bazarr


#
# MEDIA SERVICES
#
# About folder strucutre in media server
# https://trash-guides.info/Hardlinks/How-to-setup-for/Docker/
media_dir:     /media
download_dir:  /media/torrents
movie_dir:     /media/streaming/movies
tv_dir:        /media/streaming/tv


#
# SSH (geerlingguy.security)
#
# security_ssh_port: 69
# security_sudoers_passwordless: ['{{ username }}']
# security_autoupdate_reboot: true
# security_autoupdate_mail_to: '{{ email }}'
# security_autoupdate_reboot_time: '23:00'
# security_autoupdate_mail_on_error: false
