#
# Misc
#
username: "talisoon"
shell: /usr/bin/fish
timezone: America/Recife

home_dir: "/home/{{ username }}"

#
# Docker apps
#
docker_dir:         "{{ home_dir }}/docker"
docker_data_dir:    "{{ home_dir }}/docker/data"
docker_compose_dir: "{{ home_dir }}/docker/composes"

# Composes files
services_source_ddsdr: "{{ playbook_dir }}"
services_source_dir: "{{ playbook_dir }}/services"

#
# Packages
#
essential_packages:
  - fish
  - git
  - vim
  - htop
  - tmux
  - speedtest-cli
  - stow
  - exa
  - bat
  - lm-sensors
  - tree
  - wget
  - curl
  - traceroute

extra_packages:
  - neofetch
  - neovim

#
# SSH (geerlingguy.security)
#
# security_ssh_port: 69
# security_sudoers_passwordless: ['{{ username }}']
# security_autoupdate_reboot: true
# security_autoupdate_mail_to: '{{ email }}'
# security_autoupdate_reboot_time: '23:00'
# security_autoupdate_mail_on_error: false
