#
# Misc
#
username: "orangepi"
shell: /usr/bin/fish
timezone: America/Recife

home_dir: "/home/{{ username }}"

host: "192.168.1.18"

#
# Docker apps
#
docker_dir:         "{{ home_dir }}/docker"
docker_compose_dir: "{{ home_dir }}/docker/composes"
docker_services_dir:    "{{ home_dir }}/docker/services"

# Composes files
containers_config_dir: "{{ playbook_dir }}/containers"

#
# Packages
#
essential_packages:
  - fish
  - git
  - vim
  - htop
  - tmux
  - speedtest-cli
  - stow
  - exa
  - bat
  - lm-sensors
  - tree
  - wget
  - curl
  - traceroute
  - apparmor # Needed by docker in Debian

extra_packages:
  - neofetch
  - neovim
  - ranger


#
# MEDIA SERVICES
#
# About folder strucutre in media server
# https://trash-guides.info/Hardlinks/How-to-setup-for/Docker/
media_dir:     /media
download_dir:  /media/torrents
movie_dir:     /media/streaming/movies
tv_dir:        /media/streaming/tv

#
# Services
#
services:
  # System-admin --------------
  - title: Portainer
    name: portainer
    port: 9443
    type: system-admin

  - title: Cockpit
    name: cockpit
    port: 9090
    type: system-admin

  - title: Homepage
    name: homepage
    port: 3000
    type: system-admin

  # Media ---------------------
  - title: Qbittorrent
    name: qbittorrent
    port: 13000
    type: media

  - title: Jellyfin
    name: jellyfin
    port: 8096
    type: media

  - title: Jellyseerr
    name: jellyseerr
    port: 5055
    type: media

  - title: Radarr
    name: radarr
    port: 7878
    type: media

  - title: Sonarr
    name: sonarr
    port: 8989
    type: media

  - title: Prowlarr
    name: prowlarr
    port: 9696
    type: media

  - title: Bazarr
    name: bazarr
    port: 6767
    type: media

services_names: "{{ services | map(attribute='name') }}"


#
# SSH (geerlingguy.security)
#
# security_ssh_port: 69
# security_sudoers_passwordless: ['{{ username }}']
# security_autoupdate_reboot: true
# security_autoupdate_mail_to: '{{ email }}'
# security_autoupdate_reboot_time: '23:00'
# security_autoupdate_mail_on_error: false
