---
- name: Copy compose file
  template:
    src: "{{ containers_config_dir }}/homepage/docker-compose.yaml.j2"
    dest: "{{ docker_compose_dir }}/homepage/docker-compose.yaml"

- name: Make sure that the config folders exists
  ansible.builtin.file:
    path: "{{ docker_services_dir }}/homepage/config"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory

- name: Copy configurations
  copy:
    src: "{{ item }}"
    dest: "{{ docker_services_dir }}/homepage/config/{{ item | basename }}"
  with_fileglob:
    - "{{ containers_config_dir }}/homepage/config/*"

- name: Setup compose file
  docker_compose:
    project_src: "{{ docker_compose_dir }}/homepage"
    state: present
