---
- name: Ensure volume is created
  community.docker.docker_volume:
    volume_name: portainer_data

- name: Copy compose file
  copy:
    src: "{{ services_source_dir }}/portainer/docker-compose.yaml"
    dest: "{{ docker_compose_dir }}/portainer/docker-compose.yaml"

- name: Setup compose file
  docker_compose:
    project_src: "{{ docker_compose_dir }}/portainer"
    state: present
