---
- name: Install Python and python3-pip
  become: true
  package:
    name:
      - python3
      - python3-pip
    state: present

- name: Install docker module for Python
  become: true
  pip:
    name:
      - docker
      - docker-compose

- name: Make sure that the docker folders exists
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
  loop:
    - "{{ docker_dir }}"
    - "{{ docker_compose_dir }}"
    - "{{ docker_services_dir }}"
    - "{{ download_dir }}"
    - "{{ movie_dir }}"
    - "{{ tv_dir }}"

- name: Chmod the docker directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"
    recurse: yes
  loop: 
    - "{{ docker_dir }}"
    - "{{ docker_compose_dir }}"
    - "{{ docker_services_dir }}"
    - "{{ download_dir }}"
    - "{{ movie_dir }}"
    - "{{ tv_dir }}"

- name: Make sure that the services - compose folders exists
  ansible.builtin.file:
    path: "{{ docker_compose_dir }}/{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
  loop: "{{ services_names }}"

- name: Make sure that the services - services folders exists
  ansible.builtin.file:
    path: "{{ docker_services_dir }}/{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
  loop: "{{ services_names }}"
