---
- name: Install Python and python3-pip
  package:
    name:
      - python3
      - python3-pip
    state: present

- name: Install docker module for Python
  pip:
    name:
      - docker
      - docker-compose

- name: Make sure that the docker folders exists
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ username }}"
    state: directory
  loop:
    - "{{ docker_compose_dir }}"
    - "{{ docker_dir }}"

- name: Setup service -> "{{ item }}"
  include_tasks: "{{ item }}.yaml"
  loop:
    - portainer
