---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services

- Settings:
    - Portainer:
        href: https://192.168.1.18:9443/
        icon: portainer.png
        container: portainer
    - Cockpit:
        href: https://192.168.1.18:9090/
        icon: cockpit.png

- Media:
    - Qbittorrent:
        href: http://192.168.1.18:13000/
        icon: qbittorrent.png
        container: qbittorrent
        widget:
            type: qbittorrent
            url: http://192.168.1.18:13000
            username: admin
            password: adminadmin

    - Jellyfin:
        href: http://192.168.1.18:8096/
        icon: jellyfin.png
        container: jellyfin

    - Radarr:
        href: http://192.168.1.18:7878/
        icon: radarr.png
        container: radarr
    
    - Sonarr:
        href: http://192.168.1.18:8989/
        icon: sonarr.png
        container: sonarr
    
    - Bazarr:
        href: http://192.168.1.18:6767/
        icon: bazarr.png
        container: bazarr

    - Prowlarr:
        href: http://192.168.1.18:9696/
        icon: prowlarr.png
        container: prowlarr

