---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings

theme: dark
color: slate
favicon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/xcp-ng.png
hideVersion: true

layout:
  Settings:
    columns: 5
    style: row
  Media:
    columns: 5
    style: row

quicklaunch:
    searchDescriptions: true
    hideInternetSearch: true
    hideVisitURL: false

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey